### ISSUE TITLE
IUserClaimsPrincipalFactory CreateAsync Throws error after upgrade

### ISSUE THREAD

**Issue by hakeemoriola** [matteofabbri/AspNetCore.Identity.Mongo#45]
Can you help resolve this 

System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at AspNetCore.Identity.Mongo.Stores.RoleStore`1.GetClaimsAsync(TRole role, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`2.GenerateClaimsAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1.CreateAsync(TUser user)
   at infusync.identity.ProfileService.GetProfileDataAsync(ProfileDataRequestContext context) in /Users/hakeemoriola/Documents/GitHub/infusync/infusync.identity/ProfileService.cs:line 37
   at IdentityServer4.Services.DefaultClaimsService.GetAccessTokenClaimsAsync(ClaimsPrincipal subject, Resources resources, ValidatedRequest request)
   at IdentityServer4.Services.DefaultTokenService.CreateAccessTokenAsync(TokenCreationRequest request)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.CreateAccessTokenAsync(ValidatedTokenRequest request)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessTokenRequestAsync(TokenRequestValidationResult validationResult)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessAsync(TokenRequestValidationResult request)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by vova3211** [comment]
Hi @hakeemoriola!
In previous versions of library class `AspNetCore.Identity.Mongo.Stores.RoleStore<TRole>` wasn't implemented interface `Microsoft.AspNetCore.Identity.IRoleClaimStore<TRole>`. So new `TRole` entity has one more field - `List<IdentityRoleClaim<string>> Claims`.

I guess in db you have roles smth like:
```
{
    "_id" : ObjectId("5e88749c85924566b02855cd"),
    "Name" : "Admin",
    "NormalizedName" : "ADMIN",
    "ConcurrencyStamp" : "26b383db-ca7c-46fc-987b-cd8fecb1a54e"
}
```

You need to update your role collection like:
```
{
    "_id" : ObjectId("5e88749c85924566b02855cd"),
    "Name" : "Admin",
    "NormalizedName" : "ADMIN",
    "ConcurrencyStamp" : "26b383db-ca7c-46fc-987b-cd8fecb1a54e",
    "Claims" : [ ]
}
```

**Comment by hakeemoriola** [comment]
Thanks @vova3211
